### ISSUE TITLE
Unnecessary [unowned self] in documentation

### ISSUE THREAD

**Issue by fredpi** [Dschee/Imperio#6]
In the documentation, it reads

> Please don't forget the [unowned self] when using @escaping closures to prevent memory leaks.

... referencing the following example:

```
func imagePickerStartButtonPressed() {
    let imagePickerFlowCtrl = ImagePickerFlowController { [unowned self] pickedImage in
        // do something with the result
    }

    add(subFlowController: imagePickerFlowCtrl)
    imagePickerFlowCtrl.start(from: mainViewController!)
}
```

Actually, when the flow controller doesn't hold a strong reference to the child flow controller apart from the one which is created by using `add(subFlowController: imagePickerFlowCtrl)`, there should be no issues.

When `removeFromSuperFlowController()` gets called as it is supposed to, the flow controller will no longer keep a reference to the sub flow controller. As nothing points to the sub flow controller any longer, it can be cleared, despite not using `[unowned self]`.

Therefore, this declaration is not necessary and should not be proposed in the documentation.

Only case for using `[unowned self] would be when the flow controller keeps a strong reference to the sub flow controller in a variable. Yet, to my understanding, this is not the suggested way to use flow controllers, is only required rarely and doesn't fit the example given in the documentation.

**Comment by mrylmz** [comment]
Actually thats not right. The FlowController is holding a strong reference to the `imagePickerFlowCtrl` as soon as `-add(subFlowController:)` gets called. 

If you do not pass the parent FlowController as an unowned reference there will be a retain cycle, because the `ImagePickerFlowController` is holding a strong reference to the closure. 

You should only discard `[unowned self]` or `[weak self]` if the closure is non escaping.

**Comment by fredpi** [comment]
As soon as `removeFromSuperFlowController()` gets called (which is the suggested way to handle it), the retain cycle is cleared:

```
/// Removes this flow controller from its super flow controller.
 public func removeFromSuperFlowController() {
     superFlowController?.subFlowController = nil
     superFlowController = nil
 }
```

**Comment by mrylmz** [comment]
Consider a situation where you are calling `-removeFromSuperFlowController` on a parent. Then you will lose as you mentioned all strong references to the `FlowController` except the one in the closure. 

This will potentially lead to a memory leak.

**Comment by fredpi** [comment]
That's true, yet as far as my understanding goes, it's not a suggested use case to remove a flow controller from its parent when it still has a `subFlowController`, at least not if this `subFlowController` holds a completion handler.

However, since there isn't any use case for a flow controller to keep its sub flow controller when it is removed from its parent flow controller, I'd suggest to change the `removeFromSuperFlowController()` implementation:

```
/// Removes this flow controller and its nested sub flow controllers from their respective super flow controllers.
public func removeFromSuperFlowController() {
    subFlowController?.removeFromSuperFlowController()
    superFlowController?.subFlowController = nil
    superFlowController = nil
}
```

This would allow not to use `[unowned self]` as long as the flow controller isn't stored in an additional variable.

**Comment by Jeehut** [comment]
Actually, my personal opinion is that when using @escaping closures, it's always safer to use `unowned self` or `weak self` (I always prefer the first if it works, and it works most of the time in UI classes). I've got the feeling that many developers are on the wrong impression that there's a garbage collector in place on iOS / Swift, but there's not. ARC is still reference counting and references aren't cleaned up during runtime, instead things are pretty static. So, even if this specific use case in the README would not require an `unowned self` I would definitely keep it their because developers should get used to adding `unowned` or `weak` for @escaping closures, always. It's a rule similar to "Try to never use force unwrapping types" – sometimes one might know it's actually okay to use them, but it's still considered bad smell. For me, this is the same.

Having this said, nothing speaks against merging #8. So, doing it now.
